# Generated by Django 3.0.8 on 2020-08-02 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea_ind',
            name='detalles',
            field=models.TextField(default=' ', max_length=300),
        ),
    ]
